#!/usr/bin/env python3
"""
Generate dense mel filterbank constants for firmware and host-side CMSIS DSP.

The runtime uses arm_mat_vec_mult_f32(), so the generated matrix is stored in
row-major order as [mel_bin][fft_bin].

Outputs:
  - firmware/include/mel_constants.h
  - firmware/src/mel_constants.c
"""

from __future__ import annotations

import os

import numpy as np
import tensorflow as tf


# Must match firmware configuration.
SAMPLE_RATE = 16000
FFT_LENGTH = 512
NUM_MEL_BINS = 40
LOWER_EDGE_HERTZ = 20.0
UPPER_EDGE_HERTZ = 4000.0
NUM_FFT_BINS = (FFT_LENGTH // 2) + 1


def format_float(value: float) -> str:
    """Format a float32 constant for C source output."""
    return f"{float(np.float32(value)):.9e}f"


def format_dense_rows(dense_matrix: np.ndarray) -> list[str]:
    rows: list[str] = []
    for mel_idx, row in enumerate(dense_matrix):
        values = ", ".join(format_float(v) for v in row)
        suffix = "," if mel_idx < dense_matrix.shape[0] - 1 else ""
        rows.append(f"    /* mel bin {mel_idx:02d} */ {values}{suffix}")
    return rows


def generate_dense_filterbank() -> None:
    """Generate the dense mel matrix used by the CMSIS matrix backend."""

    # TensorFlow returns [fft_bin][mel_bin]. Transpose for row-major matrix ops.
    tf_weights = tf.signal.linear_to_mel_weight_matrix(
        num_mel_bins=NUM_MEL_BINS,
        num_spectrogram_bins=NUM_FFT_BINS,
        sample_rate=SAMPLE_RATE,
        lower_edge_hertz=LOWER_EDGE_HERTZ,
        upper_edge_hertz=UPPER_EDGE_HERTZ,
    ).numpy()
    dense_matrix = np.asarray(tf_weights.T, dtype=np.float32)

    total_elements = dense_matrix.size
    nonzero_elements = int(np.count_nonzero(dense_matrix))
    density = nonzero_elements / total_elements

    print("Mel filterbank statistics:")
    print(f"  TensorFlow shape [fft][mel]: {tf_weights.shape}")
    print(f"  Runtime shape [mel][fft]: {dense_matrix.shape}")
    print(f"  Total elements: {total_elements}")
    print(f"  Non-zero elements: {nonzero_elements}")
    print(f"  Density: {density:.2%}")

    header_path = "firmware/include/mel_constants.h"
    source_path = "firmware/src/mel_constants.c"
    os.makedirs(os.path.dirname(header_path), exist_ok=True)
    os.makedirs(os.path.dirname(source_path), exist_ok=True)

    with open(header_path, "w", encoding="utf-8") as f:
        f.write("#ifndef MEL_CONSTANTS_H\n")
        f.write("#define MEL_CONSTANTS_H\n")
        f.write("\n")
        f.write('#include "data.h"\n')
        f.write("\n")
        f.write("/*\n")
        f.write(" * Dense log-mel projection matrix for CMSIS-DSP matrix operations.\n")
        f.write(" *\n")
        f.write(" * Layout is row-major [mel_bin][fft_bin] so it can be passed directly\n")
        f.write(" * to arm_mat_vec_mult_f32() with the FFT magnitude vector.\n")
        f.write(" */\n")
        f.write("#define MEL_FILTERBANK_ROWS NUM_MEL_BINS\n")
        f.write("#define MEL_FILTERBANK_COLS NUM_FFT_BINS\n")
        f.write("#define MEL_FILTERBANK_DENSE_SIZE (MEL_FILTERBANK_ROWS * MEL_FILTERBANK_COLS)\n")
        f.write("\n")
        f.write("extern const float mel_filterbank_dense[MEL_FILTERBANK_DENSE_SIZE];\n")
        f.write("\n")
        f.write("#endif /* MEL_CONSTANTS_H */\n")

    with open(source_path, "w", encoding="utf-8") as f:
        f.write("/*\n")
        f.write(" * Dense mel filterbank generated by training/scripts/gen_mel_header.py.\n")
        f.write(" * Keep this in a single translation unit to avoid duplicate symbols.\n")
        f.write(" */\n")
        f.write("\n")
        f.write('#include "mel_constants.h"\n')
        f.write("\n")
        f.write("const float mel_filterbank_dense[MEL_FILTERBANK_DENSE_SIZE] = {\n")
        f.write("\n".join(format_dense_rows(dense_matrix)))
        f.write("\n};\n")

    print("\nGenerated files:")
    print(f"  Header: {header_path}")
    print(f"  Source: {source_path}")
    print(f"Flash footprint: ~{total_elements * 4} bytes")


if __name__ == "__main__":
    generate_dense_filterbank()
