CONFIG_USB_DEVICE_STACK=y
CONFIG_USB_CDC_ACM=y
CONFIG_USB_DEVICE_INITIALIZE_AT_BOOT=n
CONFIG_USB_DEVICE_PRODUCT="nRF Embedded ML Console"
CONFIG_USB_DEVICE_MANUFACTURER="nrf-embedded-ml-benchmarks"

CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y
CONFIG_UART_LINE_CTRL=y

CONFIG_USE_SEGGER_RTT=n
CONFIG_RTT_CONSOLE=n
